os: Visual Studio 2015

install:
    - cmd: echo Downloading Vulkan SDK.
    - cmd: curl --silent --show-error --output VulkanSDK.exe https://sdk.lunarg.com/sdk/download/1.1.85.0/windows/VulkanSDK-1.1.85.0-Installer.exe
    - cmd: echo Installing Vulkan SDK.
    - cmd: .\VulkanSDK.exe /S
    - cmd: echo Installation complete.

environment:
  VULKAN_SDK: c:\VulkanSDK\1.1.85.0
  matrix:
    - platform: x86
      configuration: Static Debug
    - platform: x86
      configuration: Static Release
    - platform: x64
      configuration: Dynamic Debug
    - platform: x64
      configuration: Dynamic Release

matrix:
  fast_finish: false

build:
  parallel: true
  project: build\visual studio\flare.sln
  verbosity: minimal