os: Visual Studio 2015

install:
    -cmd: curl --silent --show-error --output VulkanSDK.exe https://sdk.lunarg.com/sdk/download/1.1.85.0/windows/VulkanSDK-1.1.85.0-Installer.exe && .\VulkanSDK.exe /S

environment:
  VULKAN_SDK: c:\VulkanSDK\1.1.85.0
  matrix:
    - platform: x86
      configuration: Static Debug
    - platform: x86
      configuration: Static Release
    - platform: x64
      configuration: Dynamic Debug
    - platform: x64
      configuration: Dynamic Release

matrix:
  fast_finish: false

build:
  parallel: true
  project: "build\visual studio\flare.sln"
  verbosity: minimal